---

- hosts: all
  gather_facts: false
  tasks:

  - name: Create a User
    tower_user:
      first_name: Joe
      last_name: User
      username: joe
      password: secret
      email: joe@example.org
      state: present
      verify_ssl: false

  - name: Create an Auditor
    tower_user:
      first_name: Joe
      last_name: Auditor
      username: joe
      password: secret
      email: joe@example.org
      state: present
      auditor: true
      verify_ssl: false

  - name: Create a Superuser
    tower_user:
      first_name: Joe
      last_name: Super
      username: joe
      password: secret
      email: joe@example.org
      state: present
      superuser: true
      verify_ssl: false
